"""Ajout stock_cuisine et stock_magasin

Revision ID: 72a868cd6479
Revises: 
Create Date: 2025-05-01 18:18:07.523203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a868cd6479'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_cuisine', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stock_magasin', sa.Float(), nullable=True))
        batch_op.drop_column('quantite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantite', sa.FLOAT(), nullable=True))
        batch_op.drop_column('stock_magasin')
        batch_op.drop_column('stock_cuisine')

    # ### end Alembic commands ###
